- name: CallingStation
  description: CS
  command: systemctl is-active pokrio
  url: callingstation.net

- name: Kartickator
  description: CS
  command: pm2 status kartickator
  url: vaporized.life

- name: Zomboid
  description: CS
  command: ps -aux | grep zomboid
  url: null

- name: Dev portal
  description: CS
  command: s -aux | grep servermonitor
  url: dev.vaporized.life

- name: Test fail
  description: CS
  command: 'yes'
  url: devcdfa.vaporized.life